# Generated by Django 4.1.1 on 2022-09-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.PositiveIntegerField()),
                ('brend', models.CharField(max_length=50)),
                ('miqdor', models.CharField(max_length=50)),
                ('olvchov', models.CharField(choices=[('KG', 'KG'), ('TONN', 'TONN')], max_length=50)),
                ('kelgan_sana', models.DateField(auto_now_add=True)),
                ('Ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.omborxona')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('qarz', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('Ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.omborxona')),
            ],
        ),
    ]
