# Generated by Django 4.1.1 on 2022-09-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asosiy', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy', models.IntegerField()),
                ('miqdor', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('tolandi', models.IntegerField()),
                ('nasiya', models.PositiveIntegerField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.client')),
                ('Mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot')),
                ('Ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.omborxona')),
            ],
        ),
    ]
